version: "3.9"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:20.04.1
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sofia
      - VIRTUAL_HOST=torrent.lan
      - VIRTUAL_PORT=8080
    volumes:
      - ./data/config/:/config/
      - type: bind # using the long syntax to fail container start if source is missing
        source: ${QBITTORRENT_DATA_DIR:-./data/downloads}
        target: /data/
    ports:
      - 6881:6881
      - 6881:6881/udp
