version: "3.9"

services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.4.0
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sofia
    volumes:
      - ./data/config/:/config/
      - type: bind # using the long syntax to fail container start if source is missing
        source: ${QBITTORRENT_DATA_DIR:-./data/downloads}
        target: /data/
    ports:
      - 6881:6881
      - 6881:6881/udp
