version: "3.9"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # ngrok:
  #   image: ngrok/ngrok:alpine
  #   container_name: ngrok
  #   restart: unless-stopped
  #   command: "http nginx-proxy --region=eu --inspect=false --bind-tls=true --log=stdout"
  #   environment:
  #     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}

  qbittorrent:
    extends:
      file: ./qbittorrent/docker-compose.yaml
      service: qbittorrent

  plex:
    extends:
      file: ./plex/docker-compose.yaml
      service: plex

  pihole:
    extends:
      file: ./pihole/docker-compose.yaml
      service: pihole
