version: "3.8"

services:
  plex:
    image: ghcr.io/linuxserver/plex:1.24.4
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK=022 #optional
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ${PWD}/data/config/:/config
      - ${TVSHOWS_DIR:-./data/tvshows}:/tv
      - ${MOVIES_DIR:-./data/movies}:/movies
    restart: unless-stopped