version: "3.8"

services:
  plex:
    image: ghcr.io/linuxserver/plex:1.21.4.4079-1b7748a7b-ls29
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK=022 #optional
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    ports:
      - 32400:32400
    volumes:
      - ${PWD}/data/config/:/config
      - ${TVSHOWS_DIR:-./data/tvshows}:/tv
      - ${MOVIES_DIR:-./data/movies}:/movies
    restart: unless-stopped