version: "3.8"

services:
  plex:
    image: ghcr.io/linuxserver/plex:1.25.2
    container_name: plex
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=plex.lan
      - VIRTUAL_PORT=32400
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK=022 #optional
    ports:
      - 1900:1900/udp
      - 3005:3005
      - 5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./data/config/:/config/
      - type: bind # using the long syntax to fail container start if source is missing
        source: ${PLEX_TVSHOWS_DIR:-./data/tvshows}
        target: /tv/
      - type: bind # using the long syntax to fail container start if source is missing
        source: ${PLEX_MOVIES_DIR:-./data/movies}
        target: /movies/
