version: "3.8"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    environment:
      TZ: 'Europe/Sofia'
      WEBPASSWORD: ''
    volumes:
      - ${PWD}/data/etc-pihole/:/etc/pihole/
      - ${PWD}/data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
