version: "3.9"

services:
  pihole:
    image: pihole/pihole:2021.12
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Sofia"
      WEBPASSWORD: ""
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    volumes:
      - ./data/etc-pihole/:/etc/pihole/
      - ./data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
