version: "3.8"

services:
  resilio_sync:
    container_name: resilio_sync
    # image: lscr.io/linuxserver/resilio-sync:2.7.2
    image: resilio/sync:2.7.2
    restart: unless-stopped
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    #   - TZ=Europe/Sofia
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - ${PWD}/data/config:/config
      - ../../../../:/mnt/mounted_folders/

