services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - type: bind # using the long syntax to fail container start if source is missing
        source: ./data/
        target: /root/.ollama
